[theme]

primaryColor = "#FF6F61"              # Coral Pink – vibrant buttons & accents
backgroundColor = "#FFF8E1"           # Light Cream – warm base background
textColor = "#4E342E"                 # Deep brown – soft contrast text
font = "monospace"




